version: '3'

services:
  rapsql:
    container_name: rapsqlcontainer
    image: opensemanticworld/rapsql:v0.1.1
    shm_size: '125gb'
    ports:
      - "${RAPSQL_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - shared_preload_libraries=age
    volumes:
      # - /mnt/pgdata:/var/lib/postgresql/data
      - rapsqldata:/var/lib/postgresql/data
      - /mnt/benchmark:/mnt
    command:
      - "postgres"
      # - "-c"
      # - "max_connections=32"
      - "-c"
      - "shared_buffers=10GB"
      # - "-c"
      # - "work_mem=480MB"
      - "-c"
      - "maintenance_work_mem=1GB"
      - "-c"
      - "effective_cache_size=192GB"
      # - "-c"
      # - "max_parallel_workers_per_gather=6"
      - "-c"
      - "statement_timeout=30min"
    deploy:
      resources:
        limits:
          cpus: '32'
          # memory: 16G
    networks:
      - rapsql-net

volumes:
  rapsqldata: {}

networks:
  rapsql-net:
    name: rapsql-net
    driver: bridge