########################## RAPSQLBench CONFIG ##########################
# Author(s): 
  # Andreas Räder (https://github.com/raederan)


### Database Installation config ##############################
postgres_apt_version: 15
apache_age_git_version: release/PG15/1.5.0


### Database interoperability config ##########################
graph_name: sp100

# Model options [gdm]: 
  # yars | rdfid
rapsql_model: yars

# Transpiler options [gdm]: 
  # plain | cpo1 (=L2L) | cpo2 (=L2R) | cpo3 (=L2L+L2R) | man
rapsql_transpiler: plain


### Benchmark metrics config ##################################
triples: 50000
memory: 250000
cores: 32
iterations: 1


### PostgreSQL config #########################################
statement_timeout: 1min
# shared_buffers: 64GB
# effective_cache_size: 192GB



##### MORE OPTIONS NEED TO BE ADDED IN `deploy.yml` FIRST #####
# max_connections: 32
# work_mem: 32MB
# maintenance_work_mem: 1GB
# checkpoint_completion_target: 0.9
# wal_buffers: 16MB
# default_statistics_target: 100
# random_page_cost: 1.1
# effective_io_concurrency: 200
# huge_pages: try
# min_wal_size: 1GB
# max_wal_size: 4GB
# max_worker_processes: 32
# max_parallel_workers_per_gather: 4
# max_parallel_workers: 32
# max_parallel_maintenance_workers: 4
