########## RAPSQLbench config ##########

### Database interoperability config ###
# Model options [gdm]: yars | rdfid
# Transpiler options [gdm]: plain | cpo1 (L2L) | cpo2 (L2R) | cpo3 (L2L+L2R) | man1
rapsqlmodel: yars
rapsqltranspiler: plain
graphname: sp50k

### Benchmark metrics config ###
triples: 50000
memory: 250000
cores: 32
iterations: 1


########## PostgreSQL config ##########
statement_timeout: 2min
shared_buffers: 64GB
effective_cache_size: 192GB



##### OPTIONS NEED TO BE ADDED IN `deploy-conf.yml` FIRST #####
# max_connections: 32
# work_mem: 32MB
# maintenance_work_mem: 1GB
# checkpoint_completion_target: 0.9
# wal_buffers: 16MB
# default_statistics_target: 100
# random_page_cost: 1.1
# effective_io_concurrency: 200
# huge_pages: try
# min_wal_size: 1GB
# max_wal_size: 4GB
# max_worker_processes: 32
# max_parallel_workers_per_gather: 4
# max_parallel_workers: 32
# max_parallel_maintenance_workers: 4
